language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker-compose -f docker-compose-build.yaml build --parallel
  - docker tag reverseproxy:v2 alyfawzy/reverseproxy:v2
  - docker tag udagram-frontend:v2 alyfawzy/udagram-frontend:v2
  - docker tag udagram-api-user:v2 alyfawzy/udagram-api-user:v2
  - docker tag udagram-api-feed:v2 alyfawzy/udagram-api-feed:v2

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push alyfawzy/reverseproxy:v2
  - docker push alyfawzy/udagram-frontend:v2
  - docker push alyfawzy/udagram-api-user:v2
  - docker push alyfawzy/udagram-api-feed:v2

